# Generated by Django 2.2.4 on 2020-05-13 17:06

from django.db import migrations, models
import myblogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.FileField(upload_to=myblogs.models.content_file_name),
        ),
    ]
