# Generated by Django 2.2.4 on 2020-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_auto_20200514_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
