# Generated by Django 2.2.4 on 2020-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0004_auto_20200514_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_id',
            new_name='id',
        ),
    ]
