# Generated by Django 2.2.4 on 2020-05-14 19:15

from django.db import migrations, models
import myblogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0007_auto_20200514_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.FileField(default='', upload_to=myblogs.models.content_file_name),
        ),
    ]
