# Generated by Django 2.2.4 on 2020-05-14 19:19

from django.db import migrations, models
import myblogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0009_auto_20200514_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.FileField(blank=True, default='', null=True, upload_to=myblogs.models.content_file_name),
        ),
    ]
